-- =====================================================================
--  고시 문제 은행 2/8 : 정치 (163문항)
--  출처 : 「시화산노회 고시부 목사장로 고시가이드」 예상 문제 은행
--  * 이 과목만 다시 넣습니다. 여러 번 실행해도 문제가 늘어나지 않습니다.
-- =====================================================================

delete from public.exam_questions where subject = '정치';

insert into public.exam_questions (subject, question, options, answer) values ('정치', '장로회 정치의 주권은 누구에게 있습니까?', '["목사", "장로", "교인", "노회"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '장로회 정치는 지교회 교인들이 누구를 선택하여 당회를 조직합니까?', '["목사", "집사", "전도사", "장로"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '장로회 정치의 핵심적인 운영 주체는 무엇입니까?', '["당회", "노회", "총회", "제직회"]'::jsonb, 0);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '장로회 정치를 한마디로 표현할 때 가장 적절한 것은?', '["신정 정치", "민주 정치", "감독 정치", "교황 정치"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '장로회 정치의 가장 큰 특징 중 하나는 무엇입니까?', '["목사 중심의 정치", "교황 중심의 정치", "감독 중심의 정치", "주권이 교인들에게 있는 민주 정치"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '장로회 정치의 삼심 제도에 포함되지 않는 치리회는?', '["당회", "노회", "대회", "총회"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '장로회 정치의 삼심 제도가 지향하는 바는?', '["상회의 절대적 권한 강화", "권력의 집중", "공정하고 신중한 치리 및 재판", "신속한 의사 결정"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '장로회 정치에서 주권이 교인들에게 있다는 것은 무엇을 의미합니까?', '["교인들이 자신들의 대표인 장로를 선출하여 치리권을 위임한다.", "교인들이 직접 투표로 모든 사무를 처리한다.", "목회자가 교인들의 의견을 무조건 따른다.", "교인들이 모든 결정을 직접 내린다."]'::jsonb, 0);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '로마 가톨릭과 희랍 정교회가 채택하는 교회 정치 형태는?', '["장로회 정치", "자유 정치", "감독 정치", "교황 정치"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '감리교회와 감독교회가 주로 채택하는 교회 정치 형태는?', '["장로회 정치", "감독 정치", "교황 정치", "조합 정치"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '각 지교회가 자유로이 행정을 하는 교회 정치 형태는?', '["교황 정치", "자유 정치", "조합 정치", "장로회 정치"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '각 지교회의 대표들이 조직하여 운영하는 교회 정치 형태는?', '["조합 정치", "장로회 정치", "감독 정치", "자유 정치"]'::jsonb, 0);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '당회를 조직하는 구성원은 누구입니까?', '["장로와 집사", "목사와 집사", "목사와 권사", "목사와 장로"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '당회에서 목사의 주된 역할은 무엇입니까?', '["치리권 행사", "재정 관리", "구제 사업 주관", "주일학교 운영"]'::jsonb, 0);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '당회에서 장로의 주된 역할은 무엇입니까?', '["선교사 파송", "성례 집례", "치리권 행사", "설교"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '당회가 조직되는 것은 어느 교회의 기본적인 구성 요건입니까?', '["조직 교회", "해외 지교회", "설립 준비 중인 교회", "미조직 교회"]'::jsonb, 0);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '양심의 주재는 누구뿐이라고 규정합니까?', '["국가", "목사", "하나님", "교황"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '양심의 자유에 대한 설명으로 옳은 것은?', '["누구든 타인의 양심을 강제할 수 있다.", "교회의 명령은 양심보다 우선한다.", "양심의 주재는 하나님뿐이므로 누구도 이 권리를 침해할 수 없다.", "양심의 자유는 법적 구속력이 없다."]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '양심의 자유 침해에 해당하지 않는 것은?', '["종교적 행사에 대한 강제 참여 요구", "종교적 신념에 따른 행동을 억압", "신앙고백을 근거로 한 자율적 판단", "개인의 신앙에 대한 강요"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '양심의 자유를 지켜야 하는 주된 이유는 무엇입니까?', '["사회 질서 유지를 위함", "개인의 편의를 위함", "종교 간의 평화를 위함", "하나님의 주권을 인정하고 인간의 존엄성을 보존하기 위함"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '교회의 직원 중 ''창설직''에 해당하는 인물은?', '["선지자", "집사", "전도사", "장로"]'::jsonb, 0);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '교회의 ''항존직''에 해당하는 직분은?', '["서리 집사", "권사", "안수집사", "전도인"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '다음 중 교회의 ''임시직''에 해당하는 직분은?', '["목사", "권사", "치리 장로", "12 사도"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '교회의 ''준직''에 해당하는 직분은?', '["선지자", "안수집사", "남녀 서리 집사", "강도사"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '교인으로 정의되기 위한 가장 기본적인 조건은?', '["교회에 헌금을 많이 해야 한다.", "봉사 활동에 적극적이어야 한다.", "지교회에 등록해야 한다.", "교회 직분을 맡아야 한다."]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '교인의 정의에서 ''삼위일체이신 하나님을 믿는 자''가 의미하는 바는?', '["성경 지식이 풍부해야 한다.", "특정 교단 소속이어야 한다.", "기독교의 근본 교리를 수용하는 신앙인임을 뜻한다.", "교회의 모든 규례를 반드시 지켜야 한다."]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '''그리스도인''이라는 칭호는 누구에게 붙여집니까?', '["세례를 받은 자에게만 붙여진다.", "목회자에게만 붙여진다.", "교회 봉사자에게만 붙여진다.", "지교회에 등록하여 삼위일체 하나님을 믿는 자에게 붙여진다."]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '교인이란 정의에서 ''지교회에 등록하여''라는 조건의 중요성은?', '["단순히 교인 수 확대를 위함", "교회의 통계적 관리를 용이하게 하기 위함", "교회의 재정 수입을 확보하기 위함", "교인이 특정 교회 공동체에 소속되어 영적 돌봄과 의무를 다할 수 있는 기반이 됨을 의미한다."]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '교인이 교회 헌법대로 순서에 따라 가질 수 있는 권리는?', '["재정 통제권", "교리 변경권", "청원, 소원, 상소할 권리", "목사 해임권"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '교인의 선거 및 피선거권이 중지될 수 있는 경우는?', '["헌금을 6 개월 이상 드리지 않은 경우", "교회 직분자의 지시에 불복종한 경우", "6 개월 이상 본 교회 예배에 계속 출석하지 않은 경우", "교회의 모든 행사에 불참한 경우"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '무흠 입교인이 가질 수 있는 권한은?', '["당회원권", "성찬에 참여하는 권한", "담임 목사 청빙권", "제직회 소집권"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '교인이 그리스도의 몸된 교회를 위하여 분량에 따라 가지는 것은?', '["부담", "의무", "특권", "책임"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '교회의 신급 종류에 포함되지 않는 것은?', '["서리교인", "원입교인", "학습교인", "유아세례교인"]'::jsonb, 0);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '교회에 처음 출석하여 신앙생활을 시작하는 교인의 신급은?', '["학습교인", "세례교인(입교인)", "유아세례교인", "원입교인"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '유아세례를 받은 후 자신의 신앙을 고백하고 정식 교인이 되는 신급은?', '["원입교인", "학습교인", "세례교인(입교인)", "유아세례교인"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '세례를 받기 전, 일정 기간 신앙을 배우고 문답을 통해 인정받는 신급은?', '["원입교인", "유아세례교인", "학습교인", "세례교인(입교인)"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '교인의 가장 기본적인 의무 중 하나는?', '["교회의 모든 행사에 참여하는 것", "교회 직분자가 되는 것", "교회의 정한 예배와 기도회, 모든 교회집회에 출석하는 것", "재정 사업에 투자하는 것"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '교인이 노력과 협력, 거룩한 교제로 교회 발전에 힘쓰며 사랑과 선행으로 하나님을 영화롭게 해야 하는 이유는?', '["교회의 외형적 성장을 위함", "교회의 본질적인 사명을 다하고 하나님의 영광을 드러내기 위함", "교인의 명예를 높이기 위함", "다른 교인들에게 모범을 보이기 위함"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '교인이 교회의 경비와 사업비에 대하여 성심껏 협조하며, 자선과 전도 사업 및 모든 선한 일에 노력과 금전을 아끼지 않아야 하는 이유는?', '["교회의 재정적 어려움을 해결하기 위함", "교인의 물질적인 복을 받기 위함", "다른 교인들과 비교하여 우위를 점하기 위함", "교회의 사명을 감당하고 하나님 나라 확장에 동참하기 위함"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '다음 중 교인으로서의 의무를 이행하지 않는 것으로 간주되어 직임을 면할 수 있는 행동은?', '["개인적으로 기도 생활을 소홀히 하는 것", "봉사 활동에 소극적인 것", "교회 수련회에 불참하는 것", "미신 행위, 음주, 흡연, 구타 등의 행동을 하는 것"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '전 세계에 흩어져 있는 교회이며, 삼위일체 하나님을 믿는 그리스도인들이 속한 교회의 유형은?', '["가정 교회", "지하 교회", "무형 교회", "유형 교회"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '''유형 교회''의 특징으로 옳은 것은?', '["건물이 없는 영적인 공동체만을 의미한다.", "특정 교단에 소속되지 않는다.", "전 세계에 흩어져 있는 그리스도인들의 구체적인 공동체를 포함한다.", "인간의 눈으로 직접 확인할 수 없다."]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '''무형 교회''의 본질적인 의미는 무엇입니까?', '["육안으로 볼 수 없는 건물을 가진 교회", "비밀리에 운영되는 지하 교회", "조직이나 제도가 없는 자유로운 공동체", "모든 신자들이 영적으로 하나님과 연결된 총체적 공동체"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '지교회 설립의 5 대 요건 중 가장 먼저 언급되는 것은?', '["일정한 장소", "교인", "거룩한 생활", "공동 예배"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '지교회 설립 요건 중 ''예수를 믿는다고 공언하는 교인들이 모여야 하는'' 것은 어떤 의미입니까?', '["세례를 받은 자들만 모여야 한다.", "예수 그리스도에 대한 신앙고백을 가진 자들의 공동체가 필수적임을 의미한다.", "단순히 사람 수가 많아야 한다는 의미이다.", "교회의 직분자들이 모여야 한다."]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '지교회 설립 요건 중 ''성경에 교훈한 대로 교회 시간을 정하여 공동 예배로 회집해야 하는'' 것의 중요성은?', '["예배 시간을 효율적으로 관리하기 위함", "교회가 공적인 예배를 통해 공동체성을 형성하고 신앙을 고백하는 것이 중요함을 의미한다.", "모든 교회가 동일한 예배 형식을 따르기 위함", "예배 시간을 규칙적으로 지키기 위함"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '당회가 조직된 교회를 무엇이라고 부릅니까?', '["조직 교회", "미조직 교회", "독립 교회", "개척 교회"]'::jsonb, 0);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '당회가 조직되지 않은 교회를 무엇이라고 부릅니까?', '["조직 교회", "협력 교회", "자립 교회", "미조직 교회"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '조직 교회와 미조직 교회를 구분하는 가장 중요한 기준은?', '["건물의 유무", "교인의 수", "재정의 자립 여부", "당회의 조직 여부"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '미조직 교회가 조직 교회가 되기 위해 필요한 가장 중요한 절차는?', '["당회 조직", "재정 자립", "새 건물 건축", "교인 수 증가"]'::jsonb, 0);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '목사 되기를 자원하는 자가 서류를 제출하는 곳은?', '["총회", "신학교", "소속 노회", "소속 교회 당회"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '노회는 목사후보생의 서류를 접수한 후 무엇을 면밀히 시험합니까?', '["사회봉사 경력", "목사가 되기에 합당한지 여부", "건강 상태", "재정 상태"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '목사후보생은 노회의 허락을 받은 후 어디에 입학하여 신학 교육을 받습니까?', '["개인적으로 선택한 신학교", "총회에서 지정하는 신학교", "사이버 신학교", "해외 신학교"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '목사후보생 과정에서 가장 중요하게 요구되는 것은?', '["빠른 시간 내에 목사가 되는 것", "노회의 지도 아래 체계적인 신학 교육을 이수하는 것", "학위 취득에만 집중하는 것", "개인적인 영적 체험만을 강조하는 것"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '목사후보생, 전도사,강도사는 교회의 어떤 직원으로 분류됩니까?', '["준직", "항존직", "임시직", "창설직"]'::jsonb, 0);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '목사후보생, 전도사,강도사 개인의 교적은 어느 치리회 하에 있습니까?', '["총회", "소속 교회와 당회", "노회", "신학교"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '목사후보생, 전도사,강도사의 직무상 치리는 어느 치리회에서 받습니까?', '["노회", "당회", "총회", "개인이 소속된 교회"]'::jsonb, 0);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '준직원으로서 목사후보생, 전도사, 강도사가 이중적인 소속(교회/당회 및 노회)을 가지는 이유는?', '["특정 치리회의 권한을 약화시키기 위함", "각자의 편의를 위함", "권한 분쟁을 유발하기 위함", "직무의 특수성과 권한의 명확화를 위함"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '집사 선택의 기준으로 제시되지 않은 것은?', '["선한 명예", "지혜와 분별력", "뛰어난 재정 능력", "진실한 믿음"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '집사의 행위가 무엇에 합당해야 한다고 규정합니까?', '["사회 법규", "교회의 전통", "목사의 지시", "복음"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '집사의 생활은 다른 사람에게 어떤 모습이 되어야 합니까?', '["조언자", "모범", "경쟁자", "심판자"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '집사가 존중을 받는 이유 중 하나는?', '["많은 재산", "높은 학력", "오랜 교회 출석", "지혜와 분별력"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '집사의 직무 수행 시 감독과 지시를 받는 대상은?', '["노회", "당회", "총회", "제직회"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '교회에서 수납된 구제비와 일반 재정을 관리하고 지출하는 직무는 누구에게 있습니까?', '["권사", "집사", "장로", "목사"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '집사가 돌봐야 할 대상에 포함되지 않는 것은?', '["재정적으로 풍요로운 자", "환자", "갇힌 자", "빈핍하고 곤궁한 자"]'::jsonb, 0);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '집사의 직무는 주로 어떤 봉사의 영역에 초점을 맞춥니까?', '["설교와 교훈", "재정 관리와 구제 봉사", "선교 전략 수립", "치리와 감독"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '장로가 되기 위한 최소 연령 기준은?', '["만 30 세 이상", "만 35 세 이상", "만 40 세 이상", "만 45 세 이상"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '장로의 자격 중 ''흠 없이 5 년 경과''는 무엇을 의미합니까?', '["세례를 받은 후 5 년", "특정 직분을 맡은 후 5 년", "교인으로서 신앙생활과 품행에 흠결 없이 5 년 이상 경과", "교회 건축 봉사 5 년"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '장로에게 요구되는 능력 중 하나는?', '["성례 집례 능력", "재정 증식 능력", "뛰어난 설교 능력", "상당한 식견, 통솔력"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '디모데전서 3 장 1-7 절은 주로 누구의 자격에 대해 언급하고 있습니까?', '["전도사", "집사", "권사", "장로 (또는 감독)"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '장로의 직무가 아닌 것은?', '["강도와 교훈", "각 항 헌금 수집 주관", "교인의 신앙과 행위 감독", "치리회에서 목사와 협력하여 사무 처리"]'::jsonb, 0);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '장로가 목사와 협력하여 사무를 처리하는 회는?', '["제직회", "공동의회", "선교회", "치리회"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '디모데전서 5 장 17 절은 장로의 어떤 역할을 지지하는 구절로 인용됩니까?', '["선교 활동", "재정 관리", "강도와 교훈", "치리하는 장로"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '장로의 권한과 직무 범위가 제한되는 주된 이유는?', '["장로의 책임감을 줄이기 위함", "교회의 효율적 운영을 위함", "목사와 장로의 직무가 서로 구별되기 때문", "목사의 권한을 강화하기 위함"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '전도사의 자격 요건으로 제시된 학력은?', '["고등학교 졸업 이상", "신학 박사 학위 소지자", "4 년제 대학 졸업 이상", "신학교 재학생 및 졸업자 또는 총신대학교 신학대학원 졸업자"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '전도사 자격 인가를 최종적으로 하는 곳은?', '["신학교", "노회", "소속 교회 당회", "총회"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '전도사가 고시 인가를 받는 이유는?', '["전도사로서의 자격과 사역의 정당성을 인정받기 위함", "교회 직분자가 되기 위함", "목사 안수를 받기 위함", "정식 교인으로 인정받기 위함"]'::jsonb, 0);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '전도사는 교회의 직원 중 어느 직분에 해당합니까?', '["항존직", "창설직", "준직", "임시직"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '목사가 되기 위한 최소 학력 요건은?', '["신학교 졸업", "총신대학교 신학대학원 및 총회 신학원 졸업", "신학 박사 학위", "특정 대학교 졸업"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '목사의 자격으로 제시된 인격적 요소 중 하나는?', '["학식이 풍부하고 행실이 선량하며 신앙이 진실해야 함", "부유한 재산", "뛰어난 언변", "많은 교인 수"]'::jsonb, 0);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '목사에게 요구되는 능력 중 ''교수에 능해야 한다''는 것은 무엇을 의미합니까?', '["성경 진리를 잘 가르치고 전달하는 능력이 있어야 한다.", "교회의 교육 프로그램을 잘 운영해야 한다.", "대학교에서 교수로 재직할 수 있어야 한다.", "학문적 연구에 능해야 한다."]'::jsonb, 0);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '목사의 자격 중 최소 연령 기준은? (단, 군목과 선교사는 예외)', '["만 25 세 이상", "만 27 세 이상", "만 29 세 이상", "만 35 세 이상"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '목사의 직무 중''지교회를 관리하는 일''에 해당하지 않는 것은?', '["재정 집행권", "성례 집례", "당회장권 행사", "예배 인도"]'::jsonb, 0);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '목사의 직무 중 ''종교상 도리와 본분을 교훈하는 일''은 주로 어떤 사역을 통해 이루어집니까?', '["재정 관리", "설교", "구제 사업", "심방"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '목사가 선교사로 나아가 수행할 수 있는 직무는?', '["군대 입대", "학문 연구", "성례 거행 및 교회 설립", "정치 참여"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '목사의 직무 중 ''복음 전파를 위해 기독신문과 서적을 출판하는 일''은 무엇을 강조합니까?', '["문서 선교의 중요성", "재정 수익 창출", "목사의 개인적인 출판 활동", "인쇄 기술의 발전"]'::jsonb, 0);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '목사 청빙 절차에서 가장 먼저 이루어져야 하는 것은?', '["노회에 청빙서 제출", "투표 진행", "공동의회 소집", "당회의 결의"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '목사 청빙을 위한 공동의회는 얼마 전에 소집되어야 합니까?', '["5 일 전", "한 달 전", "일주일 전", "3 일 전"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '목사 청빙 시 공동의회 투표에서 얻어야 하는 찬성 비율은?', '["과반수", "3 분의 2 이상", "만장일치", "4 분의 3 이상"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '공동의회에서 청빙서 작성을 담당하는 사람은?', '["임시 당회장", "당회장", "투표자 전원", "공동의회 회장"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '위임 목사는 누구의 청빙으로 노회의 위임을 받은 목사입니까?', '["지교회", "당회", "개인 교인", "제직회"]'::jsonb, 0);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '위임 목사가 본 교회를 떠나 얼마 이상 결근하게 되면 자동으로 위임이 해제됩니까?', '["3 개월 이상", "6 개월 이상", "1 년 이상", "2 년 이상"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '위임 목사 제도가 가지는 가장 큰 장점은?', '["목회자의 장기적이고 안정적인 목회 활동 보장", "교회의 빠른 성장 유도", "교인의 자유로운 목사 선택권 강화", "목사의 재정적 안정성 보장"]'::jsonb, 0);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '조직교회 시무 목사를 청빙할 때 공동의회에서 얻어야 하는 출석 교인의 찬성 비율은?', '["만장일치", "3 분의 2 이상", "4 분의 3 이상", "과반수"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '조직교회 시무 목사의 시무 기간은 몇 년입니까?', '["1 년", "2 년", "3 년", "5 년"]'::jsonb, 0);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '미조직교회 시무 목사의 시무 기간은 몇 년입니까?', '["1 년", "2 년", "3 년", "5 년"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '미조직교회 시무 목사의 시무 기간 연기 청원을 할 때 노회에 청원할 수 있는 사람은?', '["제직회장", "교인 대표", "임시 당회장", "당회장"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '부목사는 치리권이 있습니까?', '["있다", "없다", "경우에 따라 다르다", "노회에서 결정한다"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '부목사가 당회원이 될 수 없는 주된 이유는?', '["치리권이 없기 때문", "담임 목사의 지도를 받기 때문", "시무 기간이 정해져 있기 때문", "교인 수가 적기 때문"]'::jsonb, 0);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '부목사의 역할은 주로 무엇입니까?', '["교회 행정 전반 총괄", "담임 목사를 보좌하고 교인들을 심방, 교육하는 사역", "당회 의사 결정", "교회의 재정 집행"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '부목사에게 당회원권이 없는 것은 장로회 정치의 어떤 원칙과 관련이 있습니까?', '["봉사직 원칙", "항존직 원칙", "민주주의 원칙", "치리권의 명확한 구분 원칙"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '원로 목사가 되기 위한 동일한 교회에서의 최소 시무 기간은?', '["10 년 이상", "15 년 이상", "20 년 이상", "25 년 이상"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '원로 목사 추대를 위한 결의는 어디에서 이루어집니까?', '["당회", "노회", "제직회", "공동의회"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '원로 목사의 명예직을 최종적으로 허락하는 곳은?', '["당회", "공동의회", "총회", "노회"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '원로 목사가 당회의 언권 회원이 된다는 것은 무엇을 의미합니까?', '["당회 결의에 투표할 수 있다.", "당회에서 발언할 수 있으나 투표권은 없다.", "당회에 참석할 필요가 없다.", "당회의 모든 사무를 주관할 수 있다."]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '목사의 사면 종류는?', '["자유 사면, 권고 사면", "자유 사면, 조건부 사면", "임시 사면, 영구 사면", "권고 사면, 강제 사면"]'::jsonb, 0);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '목사의 사직 종류는?', '["임시 사직, 영구 사직", "권고 사직, 강제 사직", "자유 사직, 조건부 사직", "자유 사직, 권고 사직"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '목사가 스스로 직을 그만두고자 할 때 선택할 수 있는 사면/사직의 종류는?', '["권고 사면", "자유 사면 또는 자유 사직", "강제 사면", "권고 사직"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '교회 또는 노회의 권고에 의해 직무를 내려놓는 종류는?', '["임시 사직", "권고 사면 또는 권고 사직", "자유 사직", "자유 사면"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '직은 그대로 두고 시무만 하지 않겠다는 뜻은 무엇입니까?', '["은퇴", "사직", "휴직", "사면"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '직이 없는 일반 신도가 되겠다는 뜻은 무엇입니까?', '["면직", "휴직", "사직", "사면"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '목사직을 영구히 내려놓고 평신도로 돌아가는 것을 의미하는 것은?', '["정직", "사면", "사직", "시무 중지"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '목사직은 유지하되, 현재의 시무 교회에서만 직무를 하지 않는 상태를 의미하는 것은?', '["면직", "사직", "은퇴", "사면"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '한 지교회를 치리하는 회는 무엇입니까?', '["총회", "노회", "대회", "당회"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '일정한 지방 내에 교회를 치리하는 회는 무엇입니까?', '["총회", "당회", "노회", "대회"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '3 개 노회 이상으로 조직된 회는 무엇입니까?', '["당회", "노회", "총회", "대회"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '당회 조직의 요건으로 제시된 세례 교인의 최소 수는?', '["10 인 이상", "15 인 이상", "20 인 이상", "25 인 이상"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '당회 조직에 반드시 포함되어야 하는 직분은?', '["목사와 집사", "지교회의 목사와 치리 장로", "치리 장로와 서리 집사", "목사와 권사"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '당회 조직의 요건이 충족되지 않은 교회의 형태는?', '["자립 교회", "조직 교회", "독립 교회", "미조직 교회"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '세례 교인 25 인 이상이라는 요건이 의미하는 것은?', '["봉사 활동을 위한 인력 확보", "교회의 재정적 자립을 위함", "당회를 조직할 수 있는 최소한의 성숙한 교인 공동체가 형성되어야 함을 의미한다.", "교회의 규모를 크게 하기 위함"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '당회의 직무 중 ''교인의 신앙과 행위''에 대한 역할은?', '["위로", "상담", "감독", "교육"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '당회가 주관하는 직무 중 예배와 관련된 것은?', '["예배와 성례 거행", "예배 찬양단 조직", "예배 시간 변경", "예배당 건축"]'::jsonb, 0);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '당회가 관장하는 임직은 누구에 대한 것입니까?', '["장로와 집사 임직", "전도사 임직", "목사 임직", "권사 임직"]'::jsonb, 0);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '당회가 노회에 대해 가지는 직무는?', '["노회에 총대를 파송하며 청원과 보고", "노회 결의 취소", "노회 예산 편성", "노회원 선출"]'::jsonb, 0);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '당회의 권한 중 예배 의식 전반에 대한 것은?', '["예배 의식 전반 관장", "예배자 배치", "예배 음악 선정", "예배 순서 변경"]'::jsonb, 0);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '당회가 관리하는 재산에 관한 일은?', '["교회 건물의 매각 결정", "교회 재산 증식 투자", "교회 재정 전체 집행", "교회에 속한 토지, 가옥에 관한 일을 관리"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '당회의 권한은 주로 교회의 어떤 영역에 초점을 맞춥니까?', '["사회 봉사 활동 확장", "교회 내부의 영적, 행정적 질서 유지", "교단 전체의 정책 결정", "대외 선교"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '당회가 소집될 수 있는 조건 중 하나는?', '["교인 3 분의 2 이상의 청구", "목사후보생의 청구", "장로 과반수 이상의 청구", "제직회의 청구"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '본 교회 목사가 필요한 줄로 인정할 때 당회를 소집할 수 있습니까?', '["없다", "있다", "노회 허락 후 가능하다", "장로 과반수 동의 후 가능하다"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '상회의 명령이 있을 때 당회는 소집되어야 합니까?', '["공동의회 결의가 필요하다", "반드시 소집되어야 한다", "당회의 재량에 맡긴다", "필수는 아니다"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '당회 소집 권한의 목적은 주로 무엇입니까?', '["목사의 편의를 위함", "교회의 당면한 사안들을 논의하고 처리하기 위함", "장로의 권한을 강화하기 위함", "교인들의 불만을 해소하기 위함"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '당회장은 누구의 결의로 노회에 속한 목사를 대리 회장으로 세울 수 있습니까?', '["당회", "제직회", "공동의회", "총회"]'::jsonb, 0);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '대리 당회장이 될 수 있는 사람은?', '["장로", "타 교단 목사", "집사", "노회에 속한 목사"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '대리 당회장을 세우는 주된 이유는?', '["당회원들의 편의를 위함", "담임 목사의 부재 시 당회 운영을 위함", "노회의 권한을 강화하기 위함", "담임 목사의 권한을 분산하기 위함"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '대리 당회장은 원래 당회장의 모든 권한을 행사할 수 있습니까?', '["있다", "없다", "당회의 결의에 따라 다르다", "노회의 결정에 따라 다르다"]'::jsonb, 0);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '목사가 공석 중인 교회에서 장로가 당회장이 될 수 있습니까?', '["있다", "없다", "노회의 허락이 있으면 가능하다", "교인들의 동의가 있으면 가능하다"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '장로가 당회장이 될 수 없는 주된 이유는?', '["당회장은 반드시 목사여야 한다는 원칙 때문", "장로는 치리권이 없기 때문", "장로의 직무 범위가 제한되기 때문", "장로는 성례를 집례할 수 없기 때문"]'::jsonb, 0);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '목사 공석 시 당회장은 누가 대행합니까?', '["당회 내 최고령 장로", "노회가 지정하는 목사", "교회의 수석 장로", "제직회장"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '목사 공석 시 장로가 당회장 역할을 수행할 수 없다는 원칙은 장로회 정치의 어떤 특징을 보여줍니까?', '["목사의 권한 집중", "교인의 주권 강화", "교단 자율성 강화", "직분별 명확한 역할 분담"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '당회에 장로 2 인이 있는 경우, 당회 성수를 이루기 위한 최소 출석 인원은?', '["장로 1 인", "목사 1 인", "장로 1 인과 목사 1 인", "장로 2 인과 목사 1 인"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '당회에 장로 3 인 이상이 있는 경우, 당회 성수를 이루기 위한 최소 출석 인원은?', '["장로 1 인과 목사 1 인", "장로 2 인과 목사 1 인", "장로 과반수와 목사 1 인", "장로 전체와 목사 1 인"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '당회에 장로가 1 인만 있는 경우, 그 장로 치리 문제나 다른 사건에 있어 장로가 반대할 때에는 어떻게 처리합니까?', '["노회에 보고하여 처리한다.", "당회장이 단독으로 결정한다.", "교인들의 투표를 거친다.", "제직회에 결정을 위임한다."]'::jsonb, 0);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '당회 성수를 규정하는 주된 목적은?', '["당회의 의사 결정이 정당하고 합법적으로 이루어지도록 하기 위함", "당회 운영의 효율성을 높이기 위함", "당회원들의 부담을 줄이기 위함", "당회원들의 참여를 강제하기 위함"]'::jsonb, 0);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '당회 성수가 될 수 없는 경우 중 하나는?', '["세례 교인 수가 부족할 때", "장로 회원이 전원 출석하지 않을 때", "헌금이 부족할 때", "당회장(목사)이 없을 때"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '당회 성수가 될 수 없는 또 다른 경우는?', '["장로 회원이 재정 문제에 연루되었을 때", "장로 회원이 과반수 이상이 되지 않을 때", "장로 회원이 특정 활동에 불참할 때", "장로 회원이 다른 교회에 출석할 때"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '당회 성수가 미달될 때 교회가 직면할 수 있는 문제는?', '["교회 건물이 노후화된다.", "교회의 재정 문제가 발생한다.", "당회의 합법적인 의사 결정 및 사무 처리가 불가능해진다.", "교인들의 불만이 커진다."]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '당회 성수가 미달될 경우 교회가 취해야 할 조치는?', '["목사가 단독으로 결정한다.", "교인 투표를 통해 해결한다.", "성수 미달 상태로 계속 진행한다.", "상회(노회)에 보고하여 지도를 받거나 대리 당회장을 청한다."]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '노회 개회 성수를 이루기 위한 총대 장로의 최소 수는?', '["1 인 이상", "2 인 이상", "3 인 이상", "5 인 이상"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '노회 개회 성수 요건에서 ''예정한 장소와 날짜에'' 회집하는 것이 중요한 이유는?', '["편의를 위함", "노회의 합법성과 질서를 유지하고 회의의 공정성을 확보하기 위함", "노회원들의 부담을 줄이기 위함", "노회원들의 출석률을 높이기 위함"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '노회에서 총대 장로가 회원권을 갖는 시점은 언제입니까?', '["서기가 천서를 접수, 호명한 후부터", "노회 개회 시점", "천서 제출 시점", "투표 후"]'::jsonb, 0);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '총대 장로가 노회에서 회원권을 갖기 위해 필요한 서류는?', '["천서", "시무 보고서", "주민등록등본", "재정 보고서"]'::jsonb, 0);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '''천서를 접수, 호명한 후부터 회원권을 갖는다''는 규정의 목적은?', '["노회 진행을 지연시키기 위함", "노회원들에게 부담을 주기 위함", "총대 장로의 자격을 공식적으로 확인하고 질서를 유지하기 위함", "특정 장로에게 특혜를 주기 위함"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '총대 장로의 회원권 시작 시점이 중요한 이유는?', '["노회 회의의 공식적인 절차를 준수하고 그 결정에 대한 법적 효력을 부여하기 위함", "총대 장로의 개인적인 명예를 위함", "노회의 모든 안건을 신속하게 처리하기 위함", "노회원들의 참석률을 높이기 위함"]'::jsonb, 0);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '한 교회에서 20 년 이상 시무한 장로가 시무를 사임할 때 공동의회 결의로 추대되는 직분은?', '["명예 은퇴 장로", "원로 장로", "명예 장로", "은퇴 장로"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '원로 장로가 되는 기준은?', '["만 70 세 정년", "특정 봉사 경력", "교인 수 증가 기여", "20 년 이상 시무 및 공동의회 추대"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '만 70 세 정년이 되어 은퇴한 장로를 무엇이라고 합니까?', '["명예 장로", "원로 장로", "공로 장로", "은퇴 장로"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '원로 장로가 가지는 특권 중 하나는?', '["노회 총대로 파송될 수 있다.", "당회장을 대행할 수 있다.", "당회 결의에 투표할 수 있다.", "당회의 언권 회원이 된다."]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '설교와 치리를 겸한 장로를 무엇이라고 합니까?', '["목사", "강도사", "치리 장로", "원로 장로"]'::jsonb, 0);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '치리만 하는 자를 무엇이라고 합니까?', '["목사", "권사", "집사", "장로"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '목사는 어느 치리회 소속입니까?', '["제직회", "노회", "총회", "당회"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '공동의회를 소집할 수 있는 조건 중 당회의 결정은?', '["당회장이 단독으로 결정할 때", "당회원 전원의 동의가 있을 때", "당회가 필요하다고 인정할 때", "당회의 결의 없이도 가능하다"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '공동의회 소집을 위한 청원이 가능한 직분회는?', '["남선교회", "제직회", "당회", "권사회"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('정치', '상회의 명령이 있을 때 공동의회는 소집되어야 합니까?', '["반드시 소집해야 한다", "교회의 재량에 따른다", "당회의 동의가 필요하다", "필수는 아니다"]'::jsonb, 0);

select subject as "과목", count(*) as "문항" from public.exam_questions group by subject order by 1;
