-- =====================================================================
--  고시 문제 은행 4/8 : 권징조례 (154문항)
--  출처 : 「시화산노회 고시부 목사장로 고시가이드」 예상 문제 은행
--  * 이 과목만 다시 넣습니다. 여러 번 실행해도 문제가 늘어나지 않습니다.
-- =====================================================================

delete from public.exam_questions where subject = '권징조례';

insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '권징은 예수 그리스도께서 교회에 주신 무엇을 행사하며 설립하신 법도를 시행하는 것입니까?', '["권한", "사역", "섭리", "사면"]'::jsonb, 0);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '권징의 범위에 포함되는 사건의 대상은?', '["세상 사람 전체", "특정 교파", "국가 기관", "교회 내 교인, 직원, 각 치리회"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '권징은 교인과 직원, 치리회를 다스리며 무엇을 포함합니까?', '["교육 프로그램 운영", "선교 활동", "재정 관리", "권고하는 일체의 사건"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '권징이 교회에서 시행되는 궁극적인 주체는 누구입니까?', '["교인 전체", "예수 그리스도", "담임 목사", "장로"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '권징의 범위에 포함되는 대상은 무엇입니까?', '["오직 목사만을 대상으로 한다.", "교회 내의 교인, 직원, 각 치리회를 대상으로 한다.", "교회 외부의 인사들을 대상으로 한다.", "개인적인 신앙생활에만 적용된다."]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '권징이 교인에게 미치는 영향은?', '["교인의 자유를 제한하는 유일한 수단이다.", "교인의 신앙과 행위를 지도하고 권고하는 역할을 한다.", "교인의 직분을 박탈하는 역할만 한다.", "오직 처벌만을 의미한다."]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '권징의 범위에 치리회가 포함되는 이유는?', '["치리회도 위법한 행동이나 책임을 이행하지 않을 수 있기 때문", "치리회는 권징에서 예외이다.", "치리회 구성원들의 개인적인 문제를 다루기 위함", "치리회가 교회의 최고 권위이기 때문"]'::jsonb, 0);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '권징의 목적 중 범죄한 자를 위한 것은?', '["범죄자를 공개적으로 비난하는 것", "범죄자에게 육체적 형벌을 주는 것", "범죄한 자의 신령적 유익을 도모하는 것", "범죄자를 영원히 추방하는 것"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '권징의 목적이 아닌 것은?', '["덕을 세우는 것", "교회의 재정 증식", "그리스도의 권위와 존영을 견고하게 하는 것", "악행을 제거하는 것"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '권징에서 말하는 범죄의 유형으로 가장 기본적인 것은?', '["실수로 인한 잘못", "개인적인 감정 표현", "교훈과 심술과 행위가 성경에 위반되는 것", "사회적인 법률 위반"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '''악하지 아니할지라도 다른 사람으로 범죄하게 한 것''은 어떤 의미의 범죄입니까?', '["간접적인 영향으로 타인을 죄에 빠지게 한 것도 포함한다.", "직접적인 범죄만 해당한다.", "의도성이 없는 행동은 범죄로 보지 않는다.", "개인의 책임이 아니다."]'::jsonb, 0);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '''덕을 세움에 방해되게 하는 것''이 범죄로 간주되는 이유는?', '["교회의 화합과 성장에 부정적인 영향을 미치기 때문", "개인적인 감정 표현을 억압하기 위함", "교회의 명예를 실추시키기 때문", "단순히 불편함을 초래하기 때문"]'::jsonb, 0);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '교인이나 직원에 대한 범죄 사건으로 소송하는 것을 무엇이라고 합니까?', '["재판건", "행정건", "소원건", "청원건"]'::jsonb, 0);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '재판건의 특징으로 옳은 것은?', '["항상 하회에서만 처리한다.", "범죄 사건과 관련이 없다.", "하회와 상회를 불문하고 소송이 가능하다.", "오직 행정적인 문제만을 다룬다."]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '재판건 이외의 모든 것을 지칭하는 용어는?', '["행정건", "치리건", "소송건", "특별건"]'::jsonb, 0);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '다음 중 행정건에 해당하는 것은?', '["목사의 이단 사상 주장", "집사의 횡령 사건", "교회 건축 허가 요청", "장로의 비윤리적 행위"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '치리회가 재판 안건을 열기 전에 주님의 교훈대로 가장 먼저 해야 할 일은?', '["고소장을 낭독하는 것", "증거를 수집하는 것", "재판국을 조직하는 것", "먼저 화목하게 하는 것"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '''먼저 화목하게 한다''는 주님의 교훈은 어떤 성경 구절에 근거합니까?', '["고린도전서 13:4-7", "마태복음 18:15-17", "사도행전 1:8", "요한복음 3:16"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '재판 안건 개시 전 화목하게 하려는 노력의 주된 목적은?', '["불필요한 분쟁을 예방하고 관계 회복을 우선시하기 위함", "재판 과정을 생략하기 위함", "교인들에게 모범을 보이기 위함", "교회 재정 소모를 줄이기 위함"]'::jsonb, 0);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '''재판 혹 처벌 중에 있는 자''에 대하여 소송 접수를 신중히 고려해야 하는 이유는?', '["이미 다른 문제로 정신적, 법적 부담이 크기 때문", "재판 진행이 너무 쉬워지기 때문", "다른 재판에 영향을 주지 않기 위함", "그들의 죄를 면해주기 위함"]'::jsonb, 0);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '''소송을 좋아하는 성질이 있는 자''에 대한 소송 접수를 신중히 고려하는 이유는?', '["그들의 능력을 인정하기 위함", "불필요하거나 반복적인 소송으로 교회의 행정을 마비시킬 수 있기 때문", "그들의 주장이 항상 옳기 때문", "그들을 쉽게 처벌하기 위함"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '''지각이 부족한 자''에 대하여 소송 접수를 신중히 고려해야 하는 주된 이유는?', '["그들이 교회를 혼란에 빠뜨릴 수 있기 때문", "그들의 주장이 무조건 틀렸기 때문", "그들이 사회적 약자이기 때문", "그들이 자신의 행동을 제대로 이해하지 못하거나 책임질 능력이 부족할 수 있기 때문"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '소장은 무엇을 밝히 기록한 것입니까?', '["범하였다는 죄상", "개인적인 감정", "선행 기록", "재정 상태"]'::jsonb, 0);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '소장이 명확하게 작성되어야 하는 주된 이유는?', '["소송 비용을 줄이기 위함", "재판의 대상과 내용을 명확히 하여 공정한 심리를 진행하기 위함", "소송 기간을 단축하기 위함", "교인들에게 내용을 알리기 위함"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '소장에 기록된 ''죄상''은 무엇을 의미합니까?', '["피고의 재정적 문제", "피고의 성격적 결함", "피고의 신앙심 부족", "피고가 저지른 구체적인 범죄 사실"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '죄증 설명서는 무엇을 상세히 기록한 것입니까?', '["판결문 요약", "피고의 변론 내용", "재판 과정 요약", "범죄의 증거"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '죄증 설명서에 기록되어야 할 내용의 예시로 제시된 것은?', '["피고의 과거 행적, 가족 관계", "범죄의 날짜, 장소, 정황, 증인의 설명", "범죄의 동기, 피고의 심리 상태", "피해자의 감정 상태, 재정 손실액"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '죄증 설명서가 필요한 주된 이유는?', '["범죄 사실을 명확히 입증하여 공정한 재판을 돕기 위함", "재판의 신속한 진행을 위함", "피고를 미리 처벌하기 위함", "교인들에게 범죄 사실을 알리기 위함"]'::jsonb, 0);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '죄증 설명서의 역할은 소장과 어떻게 다릅니까?', '["소장은 증거를 제시하고, 죄증 설명서는 죄상을 기록한다.", "죄증 설명서는 재판 후 작성된다.", "소장은 죄상을 기록하고, 죄증 설명서는 그 죄상의 증거를 제시한다.", "둘 다 동일한 역할을 한다."]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '고소는 무엇을 구하는 소송입니까?', '["명예 회복", "화해", "책벌", "재정 지원"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '고소의 주된 목적은 무엇입니까?', '["갈등을 심화시키는 것", "범죄에 대한 합당한 책임을 묻고 교회의 질서를 회복하는 것", "개인적인 복수", "재정적 보상을 받는 것"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '고소는 누가 제기합니까?', '["치리회", "재판국", "변호인", "피해를 입은 당사자 또는 권징을 구하는 자"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '고소장은 무엇을 기록하여 무엇을 요구하는 소송 문서의 일종입니까?', '["범죄하였다는 죄상, 재판과 책벌", "재정 내역, 감사", "개인적인 불만, 사과", "선행 기록, 칭찬"]'::jsonb, 0);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '고소장의 주된 역할은?', '["피해자의 감정을 표현하는 것", "피고에게 불리한 여론을 형성하는 것", "사건을 언론에 공개하는 것", "재판이 시작될 수 있도록 공식적으로 혐의를 제기하고 책벌을 요청하는 것"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '고소장에 ''죄상''을 기록하는 것이 중요한 이유는?', '["죄를 증명할 필요가 없기 때문", "피고의 개인 정보를 노출하기 위함", "혐의의 구체성을 명시하여 재판의 초점을 분명히 하기 위함", "고소인의 감정을 표현하기 위함"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '기소는 무엇의 필요가 있어서 치리회가 원고가 되는 책벌 요구 소송입니까?', '["재정 지원", "권징", "선교 활동", "교육 프로그램"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '기소에서 원고가 되는 주체는 누구입니까?', '["제 3 자", "피해 당사자", "변호인", "치리회"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '기소가 일반적인 고소와 다른 점은 무엇입니까?', '["치리회가 자체적으로 필요성을 인정하여 제기한다.", "제 3 자가 원고가 되는 소송이다.", "재정 문제에만 국한된다.", "피해자가 직접 제기한다."]'::jsonb, 0);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '다음 중 기소가 이루어질 수 있는 상황은?', '["교인들이 재정 지원을 요청할 때", "교인이 개인적인 불만을 제기할 때", "범죄가 명백하고 교회의 질서 유지를 위해 치리회가 직접 책벌을 요구할 필요가 있을 때", "목회자가 개인적인 의견을 피력할 때"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '소원은 어떤 형식으로 상회에 제출하는 것입니까?', '["이메일로", "구두로", "전화로", "서면으로"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '소원을 제출할 수 있는 자는 누구입니까?', '["하회의 재판국원", "하회 관할에 속하여 그 치리권에 복종하는 자 중 1 인 혹은 1 인 이상", "상회의 목사", "모든 교인"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '소원이 제기될 수 있는 사건의 유형은?', '["개인적인 의견", "재판 사건", "행정 사건", "범죄 사건"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '소원을 통해 구하는 것은 무엇입니까?', '["직분 임명", "재정 지원", "하회의 책임 이행, 위법한 행동이나 결정에 대한 변경", "책벌"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '치리회가 기소할 때 원고가 되는 주체는 누구입니까?', '["제 3 자", "기소 위원 개인", "피해 당사자", "대한예수교장로회"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '대한예수교장로회가 기소 시 원고가 되는 것은 무엇을 의미합니까?', '["교단 전체의 이름과 권위로 교회의 질서를 회복하고자 함을 의미한다.", "특정 교인 개인의 권리를 대변한다.", "치리회가 개인의 책임을 회피한다.", "교단이 모든 법적 책임을 진다."]'::jsonb, 0);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '''이 밖에는 소송하는 자가 원고가 된다''는 규정은 무엇을 나타냅니까?', '["치리회가 아닌 경우, 고소를 제기하는 개인이 원고가 된다.", "모든 소송은 익명으로 진행된다.", "소송은 항상 치리회에 의해서만 시작된다.", "치리회만 원고가 될 수 있다."]'::jsonb, 0);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '치리회가 원고가 되어 기소하는 경우, 기소 위원의 역할은?', '["변호인의 역할을 한다.", "치리회의 위임을 받아 원고로서 기소 절차를 진행한다.", "재판에 참여하지 않는다.", "개인적으로 판결을 내린다."]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '재판건 성립의 세 가지 요인 중 첫 번째는?', '["피고의 자백", "증인의 증언", "원고의 고소", "치리회의 결정"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '재판건 성립의 세 가지 요인 중 두 번째는?', '["합의 요청", "재정 문제", "책벌할 만한 범죄", "행정 오류"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '재판건 성립의 세 가지 요인 중 세 번째는? (마 18:15-17 근거)', '["증거 부족", "권면해도 불응하는 악심자", "합의에 이르는 경우", "재판 회피"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '재판건이 성립되기 전에 ''권면'' 절차를 두는 주된 이유는?', '["범죄자를 미리 처벌하기 위함", "재판 과정을 복잡하게 만들기 위함", "관계 회복과 회개를 우선시하고 불필요한 재판을 방지하기 위함", "교인들에게 모범을 보이기 위함"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '재판 안건이 되지 못하는 경우 중 하나는?', '["권징조례로 금지할 일인 경우", "교회의 명예를 실추시키는 행위인 경우", "성경에 의하여 제정한 교회 규칙과 관례에 위반되지 않는 경우", "성경에 의하여 제정한 교회 규칙과 관례에 위반되는 경우"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '재판 안건이 되지 못하는 또 다른 경우는?', '["덕을 세움에 방해되는 경우", "교훈과 심술과 행위가 성경에 위반되는 경우", "권징조례로 금지할 일이 아니면", "다른 사람으로 범죄하게 한 경우"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '재판 안건이 되지 못하는 경우를 명시하는 주된 이유는?', '["모든 문제를 화해로 해결하기 위함", "재판을 최소화하기 위함", "교회의 법적 판단 기준을 명확히 하여 불필요한 소송을 방지하고 질서를 유지하기 위함", "교회 직분자들의 부담을 줄이기 위함"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '교회 규칙과 관례에 위반되지 않는 사안이 재판 안건이 될 수 없다는 것은 무엇을 강조합니까?', '["교회의 자율성", "교회의 법치주의", "교회의 법적 근거", "교회의 관습 준수"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '치리회가 재판회를 회집하면 회장이 먼저 그 이유를 공포하고 정중히 처리하기를 선언한 후 무엇을 낭독합니까?', '["회의록", "고소장과 죄증 설명서", "재판국의 국원 명단", "판결문"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '재판 회집 시 회장이 ''그 이유를 공포하고 정중히 처리하기를 선언''하는 주된 이유는?', '["교인들에게 재판의 필요성을 설명하기 위함", "재판의 시작을 알리기 위함", "재판장의 권위를 내세우기 위함", "재판의 엄중함과 공정성을 명확히 하기 위함"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '고소장과 죄증 설명서를 낭독하는 것은 재판에서 어떤 의미를 가집니까?', '["재판의 최종 결론을 미리 공개한다.", "고소인의 주장을 무조건 받아들인다.", "피고의 유죄를 확정한다.", "재판의 대상과 증거를 공식적으로 제시하여 심리의 기초를 마련한다."]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '일반 행정을 치리하는 치리회가 재판 사건이 있을 때 재판회로 모이기로 가결 지을 때 재판 사건을 다루는 당석 재판은 무엇입니까?', '["상설 재판국", "특별재판국", "재판국", "재판회"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '치리회는 무엇을 조직하여 몇 사람에게 맡겨 재판 사건을 치리하게 하는 것입니까?', '["재판국", "제직회", "당회", "노회"]'::jsonb, 0);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '기소 결정을 하는 주체는 누구입니까?', '["치리회", "제직회", "교인 전체", "당회장"]'::jsonb, 0);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '기소 결정 시 신중함이 요구되는 주된 이유는?', '["기소 과정이 복잡하기 때문", "기소가 개인의 명예와 교회 전체에 미치는 영향이 크기 때문", "기소 비용이 많이 들기 때문", "기소 후에는 번복이 불가능하기 때문"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '기소가 결정되기 전에 치리회가 고려해야 할 사항은?', '["목사의 개인적인 판단만 따른다.", "빠른 처벌만을 목적으로 한다.", "교인의 의견만 반영한다.", "증거의 명확성, 범죄의 중대성, 교회의 덕을 종합적으로 고려해야 한다."]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '노회가 재판을 관할하는 대상은 누구입니까?', '["전도사, 권사", "목사, 목사후보생, 강도사", "장로, 집사", "서리 집사"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '당회가 재판을 관할하는 대상은 누구입니까?', '["총회 소속 모든 직분자", "장로, 집사, 전도사, 권사, 서리 집사", "노회 소속 모든 직분자", "목사, 목사후보생, 강도사"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '목사후보생과 강도사의 ''교적''은 어디에 있습니까?', '["신학교", "노회", "당회", "총회"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '목사후보생과 강도사의 ''신분상 관할''은 어디에서 받습니까?', '["당회", "교육기관", "노회", "총회"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '원피고와 증인 등을 처음 소환할 때, 소환 기간은 얼마 이상으로 두어야 합니까?', '["3 일 이상", "5 일 이상", "10 일 이상", "1 개월 이상"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '소환장은 후일 무엇이 남도록 해야 합니까?', '["영상 기록", "구두 확인", "음성 기록", "송달서(배달 증명 혹 등기우편)"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '피고에게 소환장과 함께 첨부해야 하는 서류는?', '["고소장과 죄증 설명서 각 1 통", "재판국원 명단", "판결문", "참고인 진술서"]'::jsonb, 0);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '원피고와 증인 소환 방법이 구체적으로 규정되는 주된 이유는?', '["서류 작업을 간소화하기 위함", "피고의 방어권을 보장하고 재판의 공정하고 합법적인 진행을 위함", "재판 진행을 지연시키기 위함", "소환의 강제성을 높이기 위함"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '원고 혹은 피고를 위해 변호하는 사람을 무엇이라고 합니까?', '["참관인", "증인", "대리인", "변호인"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '변호인이 될 수 있는 자격은? (총회 결정 포함)', '["누구나 가능하다.", "본 장로회 목사, 장로이어야 하며, 70 세 정년 은퇴자는 될 수 없다.", "법률 전문가만 가능하다.", "사건 당사자의 가족만 가능하다."]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '사건 당사자를 대리하는 자이며, 피고가 유고 시 출석하게 하는 자는?', '["참관인", "대리인", "변호인", "증인"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '변호인과 대리인의 가장 큰 차이점은?', '["변호인은 재판에 참석하고, 대리인은 참석하지 않는다.", "변호인은 피고를 위해, 대리인은 원고를 위해 활동한다.", "변호인은 유죄를 입증하고, 대리인은 무죄를 입증한다.", "변호인은 법률적 변호를, 대리인은 당사자의 출석 대행을 한다."]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '목사를 면직할 만한 죄 중 하나는?', '["예배에 지각하는 것", "개인적인 불만을 표현하는 것", "헌금을 적게 드리는 것", "이단을 주장하는 것"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '목사를 면직할 만한 또 다른 죄는?', '["목회에 열심이 부족한 것", "설교를 짧게 하는 것", "불법으로 교회를 분립하는 행동", "교인들과 갈등을 겪는 것"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '''이단을 주장하는 것''이 목사를 면직할 만한 죄로 규정되는 주된 이유는?', '["교인들의 혼란을 야기하기 때문", "사회적으로 비난받을 수 있기 때문", "개인적인 명예를 손상시키기 때문", "교회의 근본 진리를 훼손하여 교회의 정체성을 위협하기 때문"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '''불법으로 교회를 분립하는 행동''이 목사를 면직할 만한 죄로 규정되는 이유는?', '["교회의 재정적 손실을 가져오기 때문", "목사의 개인적인 이익을 추구하기 때문", "교인들의 수가 줄어들기 때문", "교회의 일치를 깨뜨리고 분열을 조장하여 교회의 본질을 훼손하기 때문"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '담임 목사가 정직을 당하여 상소할 경우, 즉시 담임을 해제할 수 있습니까?', '["있다", "없다", "노회의 결정에 따라 다르다", "교인들의 동의가 있으면 가능하다"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '정직 처분을 받은 담임 목사가 상소하지 않으면 어떻게 됩니까?', '["정직 처분이 확정되고 그 효력이 발생한다.", "교회의 재량에 따라 복직될 수 있다.", "다른 교회로 옮길 수 있다.", "자동으로 면직된다."]'::jsonb, 0);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '이러한 규정은 교회의 재판 절차가 무엇을 중요하게 여김을 보여줍니까?', '["신속성", "상소권과 최종 판결의 확정성", "일사부재리 원칙", "하회의 권한"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '즉결 처단을 할 수 있는 경우 중 하나는?', '["교인이 개인적인 불만을 제기할 때", "목회자가 개인적인 의견을 피력할 때", "교인들이 재정 지원을 요청할 때", "치리회 석상에서 범죄한 사건"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '즉결 처단을 할 수 있는 또 다른 경우는?', '["범죄를 저지른 자가 도망쳤을 때", "타처에서 범죄한 것을 본인이 자복했을 경우", "범죄가 경미할 때", "증거가 불충분할 때"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '즉결 처단이 가능한 주된 이유는?', '["교회의 명예를 보호하기 위함", "교인들에게 강한 경고를 주기 위함", "범죄 사실이 명백하거나 자백을 통해 명확해졌기 때문에 재판 절차 없이 즉시 처결할 수 있기 때문", "재판 과정을 생략하여 신속하게 처리하기 위함"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '즉결 처단 시 치리회가 먼저 해야 할 일은?', '["바로 처벌한다.", "그 사실을 청취한 후 처결한다.", "교인들에게 의견을 묻는다.", "변호인을 선임한다."]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '노회 재판국의 국원 수는 몇 인 이상으로 정합니까?', '["5 인 이상", "6 인 이상", "7 인 이상", "9 인 이상"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '노회 재판국 국원 중 과반수는 누구로 정합니까?', '["장로", "권사", "집사", "목사"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '노회 재판국의 국원 선정 방식은?', '["추천을 통해", "자동 임명", "투표 선정", "추첨"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '노회 재판국 국원 중 목사가 과반수가 되어야 하는 주된 이유는?', '["노회 회의를 효율적으로 진행하기 위함", "목사의 수가 장로보다 많기 때문", "재판에 신학적 전문성과 영적 권위를 부여하기 위함", "목사의 권위를 강화하기 위함"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '재판국의 성수는 국원 몇 분의 몇 출석으로 이루어집니까?', '["전원", "3 분의 2", "4 분의 3", "2 분의 1"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '재판국의 성수 요건 중 또 다른 중요한 사항은?', '["과반수 이상이 평신도여야 한다.", "모든 국원이 장로여야 한다.", "반수 이상이 목사가 되어야 한다.", "특정 지역 출신이어야 한다."]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '재판국 성수 규정의 주된 목적은?', '["재판국 운영 비용을 절감하기 위함", "재판의 합법성과 공정성을 보장하여 그 결정의 효력을 강화하기 위함", "국원들의 책임감을 높이기 위함", "재판 진행을 지연시키기 위함"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '재판국 성수가 미달될 경우 발생할 수 있는 문제는?', '["재판이 더 신속하게 진행된다.", "재판 결과의 법적 효력이 인정되지 않을 수 있다.", "국원들의 부담이 증가한다.", "교회의 재정 문제가 발생한다."]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '상설 재판국은 합법적으로 해마다 국원 몇 분의 몇을 개선하는 재판국입니까?', '["3 분의 1", "전원", "2 분의 1", "4 분의 1"]'::jsonb, 0);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '상설 재판국은 사건의 유무에 불구하고 항상 조직해 두는 재판국이라는 의미인데, 이는 무엇을 강조합니까?', '["특정 사건만을 다룬다.", "재판의 임시적인 성격", "재판의 신속한 종결", "재판의 지속적인 운영과 전문성 유지"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '상설 재판국을 두는 목적은?', '["재판의 수를 늘리기 위함", "교회 내 재판 업무의 지속성과 전문성을 확보하고, 언제든지 발생할 수 있는 재판에 효율적으로 대응하기 위함", "재판국원들의 임기를 보장하기 위함", "재판 비용을 절감하기 위함"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '총회 상설 재판국은 목사 몇 인과 장로 몇 인을 국원으로 선정합니까?', '["목사 5 인, 장로 5 인", "목사 6 인, 장로 5 인", "목사 8 인, 장로 7 인", "목사 10 인, 장로 5 인"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '총회 재판국원의 성수는 몇 인으로 정합니까?', '["7 인", "9 인", "11 인", "15 인"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '총회 재판국원 성수 중 목사는 몇 인임을 요합니까?', '["4 인", "5 인", "6 인", "7 인"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '총회 상설 재판국의 구성에서 목사 인원이 장로 인원보다 많은 주된 이유는?', '["교리적, 신학적 전문성을 요구하는 최상급 재판의 특성 때문", "총회 운영을 효율적으로 하기 위함", "장로의 책임감을 줄이기 위함", "목사의 권한을 강화하기 위함"]'::jsonb, 0);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '특별 재판국이 다루는 사건의 특징은?', '["총회에서 이미 판결했으나 취소된 사건", "새롭게 제기된 사건", "간단한 행정 문제", "하회에서 해결하지 못한 사건"]'::jsonb, 0);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '특별 재판국이 판결한 후 그 결과를 누구에게 보고해야 합니까?', '["노회", "본회(총회)", "당회", "제직회"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '특별 재판국 제도가 필요한 주된 이유는?', '["총회 본회에서 발생한 오판을 바로잡고 재심의의 전문성을 확보하기 위함", "총회 본회의 부담을 줄이기 위함", "모든 사건을 특별하게 처리하기 위함", "특정 국원들에게 권한을 집중하기 위함"]'::jsonb, 0);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '재판국원이 그 재판에 대하여 투표권을 상실하게 되는 경우 중 하나는?', '["재판에 너무 열심히 참여할 때", "재판 진행에 적극적으로 기여할 때", "재판에 대한 개인적인 의견이 있을 때", "재판할 때 결석한 회원(국원)"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '지각이나 조퇴로 자초지종 임석하지 못한 회원(국원)은 어떻게 됩니까?', '["투표권을 상실한다.", "부분적으로 투표권을 행사할 수 있다.", "다음 재판에 자동으로 참여한다.", "특별히 배려한다."]'::jsonb, 0);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '재판국원이 투표권을 상실하는 또 다른 경우는?', '["원피고와 재판회(국)의 동의 승낙을 얻지 못한 회원(국원)", "재판국장의 지시를 따르지 않는 회원", "원피고와 재판회(국)의 동의 승낙을 얻은 회원(국원)", "재판 결과에 불만을 가진 회원"]'::jsonb, 0);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '재판국원의 투표권 상실 규정이 중요한 이유는?', '["특정 국원에게 특혜를 주기 위함", "재판 진행을 지연시키기 위함", "재판의 공정성과 투명성을 확보하고, 재판 과정에 온전히 참여한 자만이 판단에 참여하도록 하기 위함", "국원들의 부담을 줄이기 위함"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '치리회가 재심 청구를 거절할 수 있는 경우는?', '["재심을 통해 새로운 사실이 밝혀질 가능성이 있을 때", "재심에서 면죄할 만한 새 증거가 나타날 것이라 여겨지지 아니하면", "피고가 재심을 강력히 요구할 때", "재심 절차가 복잡할 때"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '재심 청구 거절의 주된 이유는?', '["재판국의 부담을 줄이기 위함", "재판의 종결성을 보장하기 위함", "불필요한 반복 소송으로 교회의 행정을 낭비하지 않기 위함", "피고의 권리를 침해하기 위함"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '재심 청구를 거절할 수 있다는 규정은 무엇을 강조합니까?', '["재판의 최종적 성격", "피고의 권리 제한", "치리회의 독단적 권한", "재심의 필요성"]'::jsonb, 0);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '재심 청구를 거절하기 전에 치리회가 고려해야 할 사항은?', '["재심에 대한 교인들의 여론", "새로운 증거의 유무와 그 증거가 판결을 뒤집을 만한 중요성을 가지는지 여부", "피고의 경제적 능력", "재심으로 인한 교회의 이미지 손상 여부"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '정직되었던 장로가 직무를 회복하기 위해 가장 먼저 해야 할 일은?', '["회개", "봉사 활동 참여", "교인들에게 사과", "헌금 증액"]'::jsonb, 0);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '정직되었던 장로의 직무 회복 결의는 어느 치리회에서 합니까?', '["노회", "총회", "당회", "제직회"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '장로의 직무 복직 시 교인의 가부를 기다릴 필요가 있습니까?', '["있다", "없다", "노회의 지시에 따른다", "공동의회 결의가 필요하다"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '정직되었던 장로의 직무 회복 절차가 가지는 의미는?', '["정직 처분이 가볍다는 것을 의미한다.", "교인의 의견은 중요하지 않다.", "회개와 당회의 판단을 통해 교회의 질서 안에서 직무를 회복할 기회를 준다는 의미이다.", "장로의 직무는 언제든지 복직 가능하다."]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '면직 당한 장로가 복직을 위한 첫 절차로 무엇을 해야 합니까?', '["회개", "공동의회에 출석", "교회에 재정 기부", "노회에 탄원서 제출"]'::jsonb, 0);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '면직 장로가 회개하면 당회의 결의로 무엇을 해벌하고 성찬에 참여케 합니까?', '["견책", "정직", "출교", "면직"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '면직 당한 장로가 다시 임직을 받기 위해 필요한 절차는?', '["자동으로 복직된다.", "교회가 다시 투표하여 장립 예식을 행한 후에 임직이 가능하다.", "1 년 동안 봉사하면 자동 임직된다.", "노회의 지시만 받으면 된다."]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '면직 당한 목사가 복직할 수 있는 곳은?', '["총회", "노회", "면직한 치리회 앞에서 복직하거나, 그 회의 결의대로 위탁받은 치리회", "당회"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '면직 당한 목사의 복직은 누가 최종적으로 허락합니까?', '["총회장", "해당 지교회 당회", "면직 처분을 내렸던 치리회", "교인 전체"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '면직 당한 목사가 복직하기 위해 가장 먼저 필요한 것은?', '["새로운 신학교 졸업", "교인들의 동의", "재정적 보상", "진정한 회개"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '면직 당한 목사의 복직 절차가 엄격한 주된 이유는?', '["목사의 편의를 위함", "목사직의 중요성과 면직 처분의 중대성을 반영하여 신중한 절차를 거치기 위함", "목회자의 명예를 훼손하기 위함", "다른 교회로 가지 못하게 하기 위함"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '당회 재판 없이 즉시 처결할 수 있는 경우 중 하나는?', '["교인들이 봉사 활동을 요청할 때", "목회자가 성경 공부를 지도할 때", "교인이 개인적인 고민을 토로할 때", "치리회 석상에서 범죄한 사건"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '당회 재판 없이 즉시 처결할 수 있는 또 다른 경우는?', '["증거가 불충분할 때", "범죄가 경미한 경우", "타처에서 범죄한 것을 본인이 자복했을 때", "범죄 사실이 복잡할 때"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '즉결 처단 제도가 필요한 주된 이유는?', '["재정적인 부담을 줄이기 위함", "명백한 범죄에 대해 신속하게 교회의 질서를 회복하고 죄악에 대한 단호한 입장을 표명하기 위함", "모든 재판 과정을 생략하기 위함", "교회의 명예를 보호하기 위함"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '위탁 판결을 하는 주된 이유는 무엇입니까?', '["재판을 피하기 위함", "본 회의에서 결정하기 어려운 재판 사건에 대하여 지도를 구하는 것", "모든 재판을 상회에 맡기기 위함", "하회의 책임을 회피하기 위함"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '위탁 판결은 하회의 어떤 면을 보완하기 위한 제도입니까?', '["권한 부족", "구성원 부족", "책임감 부족", "전문성 또는 판단의 어려움"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '상소는 하회에서 판결한 어떤 사건에 대하여 서면으로 상회에 제출하는 것입니까?', '["재판 사건", "인사 문제", "행정 사건", "재정 문제"]'::jsonb, 0);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '상소는 하회의 판결에 대해 무엇을 구하는 절차입니까?', '["보고", "재심 또는 변경", "승인", "감사"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '상소는 누구에게 제출합니까?', '["하회 재판국", "총회장", "개인 변호인", "상회"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '상소 제도가 필요한 주된 이유는?', '["재판 진행을 지연시키기 위함", "하회 재판의 오류나 불공정을 시정하고 재판 당사자의 권리를 보호하기 위함", "하회의 권한을 약화시키기 위함", "재판의 확정성을 강조하기 위함"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '상소할 수 있는 사유 중 ''하회가 재판을 불법하게 하는 때''는 무엇을 의미합니까?', '["재판 결과가 마음에 들지 않을 때", "재판 절차나 법규를 위반하여 재판을 진행했을 때", "재판장이 교인들과 사이가 좋지 않을 때", "재판이 너무 오래 걸릴 때"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '''하회가 상소하는 것을 불허하는 때''는 상소 사유가 됩니까?', '["아니다", "그렇다", "상회의 동의가 있어야 한다", "재판국의 결정에 따른다"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '상소 사유 중 ''불합당하게 증거를 채용하는 때''는 어떤 경우입니까?', '["모든 증거를 채용하지 않는 경우", "증거가 너무 많을 때", "증거를 너무 늦게 제출할 때", "증거 능력이 없는 것을 채용하거나, 증거 조작이 의심될 때"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '''판결 오착이나 불공평이 있는 때''가 상소 사유가 되는 주된 이유는?', '["불만을 표출할 기회를 제공하기 위함", "재판의 권위를 훼손하기 위함", "재판의 완벽성을 추구하기 위함", "하회의 판단 오류로 인해 재판 결과가 진실에 부합하지 않거나 당사자에게 불합리하게 적용되었을 때 이를 시정하기 위함"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '당회 재판에 대하여 노회에 상소하는 것을 무엇이라고 합니까?', '["재심", "공소", "소원", "상고"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '노회 재판에 대하여 총회에 상소하는 것을 무엇이라고 합니까?', '["재심", "상고", "공소", "소원"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '공소와 상고를 구분하는 가장 중요한 기준은?', '["상소하는 당사자", "재판의 결과", "상소하는 하회와 심의하는 상회", "재판의 내용"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '소원이란 무엇을 요구하는 행정 소송입니까?', '["행정 처리의 취소나 변경이나 촉구", "책벌", "직분 임명", "재정 지원"]'::jsonb, 0);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '소원장을 통해 책벌을 할 수 있습니까?', '["있다", "없다", "경우에 따라 다르다", "노회의 결정에 따른다"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '소원이 ''요구서가 아니라 행정 처리의 취소나 변경이나 촉구를 요구하는 행정 소송''이라는 것은 무엇을 강조합니까?', '["소원이 교인의 의견 표출 수단임을 강조한다.", "소원이 행정적 불합리에 대한 시정 요구임을 강조한다.", "소원이 권징의 수단임을 강조한다.", "소원이 재판 사건임을 강조한다."]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '고소나 상소 등 책벌 요구에 대한 재판국의 최후 결정은 무엇입니까?', '["판결문", "심의서", "결정서", "보고서"]'::jsonb, 0);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '행정 처결의 촉구, 변경, 취소 등을 요구하는 소원에 대한 최후 결정은 무엇입니까?', '["판결문", "보고서", "심의서", "결정서"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '판결문과 결정서의 가장 큰 차이점은?', '["판결문은 하회에서, 결정서는 상회에서만 발행된다.", "판결문은 공개되고, 결정서는 비공개이다.", "판결문은 책벌 요구에 대한 재판 결과이고, 결정서는 행정 소원에 대한 결과이다.", "판결문은 행정건에, 결정서는 재판건에 사용된다."]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '이 두 문서의 차이를 명확히 하는 이유는?', '["문서의 종류를 늘리기 위함", "책임 소재를 불분명하게 하기 위함", "행정 편의를 위함", "재판과 행정의 성격을 구분하고, 각 결정의 법적 효력과 의미를 명확히 하기 위함"]'::jsonb, 3);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '범죄 발각 후 고소를 제기할 수 있는 일반적인 기간은?', '["6 개월", "1 년", "2 년", "3 년"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '교회에 중대한 영향을 끼칠 만한 사건의 경우, 범죄 발각 후 고소를 제기할 수 있는 기간은?', '["1 년", "2 년", "3 년", "5 년"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '범죄에 대한 고소 제기 기간을 제한하는 주된 이유는?', '["범죄자를 보호하기 위함", "모든 사건을 빨리 종결하기 위함", "시간이 경과함에 따라 증거 확보가 어려워지고, 관계 회복의 기회를 주기 위함", "교회의 부담을 줄이기 위함"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '''교회에 중대한 영향을 끼칠 만한 사건''에 더 긴 공소시효를 두는 이유는?', '["중대 범죄는 그 파급력이 커서 더 오랜 기간 심의와 처벌의 필요성이 인정되기 때문", "사회 법률을 따르기 위함", "더 많은 증거를 찾기 위함", "중요하지 않은 사건은 빨리 잊기 위함"]'::jsonb, 0);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '결정에 동의하지 아니함을 밝히는 것은 무엇입니까?', '["상소", "이의", "항의", "소원"]'::jsonb, 1);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '과실 되는 것을 증명함을 밝히는 것은 무엇입니까?', '["항의", "이의", "상소", "소원"]'::jsonb, 0);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '''이의''를 제기하는 주된 목적은?', '["회의 진행을 방해하기 위함", "결정의 내용을 바꾸기 위함", "특정 결정에 대한 자신의 비동의를 공식적으로 기록하고, 향후 불복의 기초를 마련하기 위함", "다른 사람들에게 자신의 의견을 강요하기 위함"]'::jsonb, 2);
insert into public.exam_questions (subject, question, options, answer) values ('권징조례', '''항의서''를 제출하는 주된 목적은?', '["단순한 불만을 표출하기 위함", "특정 결정이나 행위의 오류나 위법성을 증명하고 시정을 요구하기 위함", "회의에 참여하지 않기 위함", "개인적인 감정을 표현하기 위함"]'::jsonb, 1);

select subject as "과목", count(*) as "문항" from public.exam_questions group by subject order by 1;
